// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfzlxchyorfaqkwvvouw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmemx4Y2h5b3JmYXFrd3Z2b3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTY2NTMsImV4cCI6MjA1NzY5MjY1M30.CwCeM3H1_lsXtJSCeVBUAyDaZFl245ezwTTsLX_D9Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);